Update binstubs

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,18 +1,42 @@
-#!/usr/bin/env bash
+#!/usr/bin/env ruby
+require 'pathname'
+require 'fileutils'
+include FileUtils
 
-set -e
+# path to your application root.
+APP_ROOT = Pathname.new File.expand_path('../', __dir__)
 
-if [ ! -e rails.git ]
-then
-    git clone --mirror git://github.com/rails/rails.git
-fi
+def system!(*args)
+  system(*args) || abort("\n== Command #{args} failed ==")
+end
 
-bundle install
+chdir APP_ROOT do
+  # This script is a starting point to setup your application.
+  # Add necessary setup steps to this file.
 
-database_config=config/database.yml
-if [ ! -e $database_config ]
-then
-    cp config/database.yml.example $database_config
-fi
+  puts '== Installing dependencies =='
+  system! 'gem install bundler --conservative'
+  system('bundle check') || system!('bundle install')
 
-bin/rails db:create:all db:schema:load
+  # Install JavaScript dependencies if using Yarn
+  # system('bin/yarn')
+
+  puts "\n== Copying sample files =="
+  unless File.exist?('config/database.yml')
+    cp 'config/database.yml.example', 'config/database.yml'
+  end
+
+  puts "\n== Cloning rails repository =="
+  unless FileTest.directory?('rails.git')
+    system! 'git clone --mirror https://github.com/rails/rails.git'
+  end
+
+  puts "\n== Preparing database =="
+  system! 'bin/rails db:setup'
+
+  puts "\n== Removing old logs and tempfiles =="
+  system! 'bin/rails log:clear tmp:clear'
+
+  puts "\n== Restarting application server =="
+  system! 'bin/rails restart'
+end
